name: testeruben
favicon: null
layout_spectrum: 0.4588891607709229
typography_spectrum: 0.6936199844349176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07273968099616468
  lightness: 0.6686415753792971
  saturation: 0.6016788564156741
  rhythmicContrast: 0.2816379051655531
purpose: []
